### PR TITLE
Upgrade sota-client library versions for hyper

### PR DESCRIPTION
**Pull request by taheris**
Part of [PRO-1674](https://advancedtelematic.atlassian.net/browse/PRO-1674).

### CODE REVIEW

**Comment by cajun-rat** [comment]
@taheris Is this PR still current--I recall you were working on this on Friday?

**Comment by taheris** [comment]
It is, but it requires coordination over several repos before merging. I'll open a PR specifying the merge order once they have all been tested.

**Comment by cajun-rat** [comment]
OK, gimme a shout when you want something tested

**Comment by taheris** [comment]
@cajun-rat: this now build against 1.10.0. Any further Rust updates will need to wait until after Yocto is upgraded.

**Comment by cajun-rat** [comment]
@OYTIS Can you coordinate merging this as part of the 'updater' changes to OpenIVI, please?  If it makes sense to copy this updated recipe to meta-updater just delete the old one from meta-oim, then go-ahead and do that.

**Comment by OYTIS** [comment]
Review score: 11/11.

**Comment by OYTIS** [comment]
I'll merge it here now, and copy it to meta-updater as well. Once we are done with OSTree on Minnowboard, sota-client can be deleted from meta-oim.

**Pull request merged**
