### PR TITLE
HTML5 headunit

### PR DESCRIPTION
**Pull request by cajun-rat**

### CODE REVIEW

**Comment by alexhumphreys** [comment]
This PR is 8 commits, that cool with you?

**Comment by cajun-rat** [comment]
yep :)

**Comment by alexhumphreys** [comment]
Cool. You know a repo command that lets me change the branch of just one repository? Or do I have to edit the repo xml file?

**Comment by cajun-rat** [comment]
I think there is repo download, but that might need gerrit. If not, can you do a got fetch; git checkout branchname in the relevant git project?

Phil

On 31 March 2016 17:41:42 CEST, Alex Humphreys notifications@github.com wrote:

> Cool. You know a repo command that lets me change the branch of just
> one repository? Or do I gave to edit the repo xml file?
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/openivimobility/meta-oim/pull/62#issuecomment-203991325

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
