### PR TITLE
Upgrade rust 1.7 -> 1.10

### PR DESCRIPTION
**Pull request by alexhumphreys**
[PRO-1474]

From this commit on we'll need to manually bump the `PV` and the `SRCREV` of sota-client when we want to update.

I used a git describe format with `s/-/_/` for the `PV`. 

If someone wants to build from a local checkout, they can use the two step build using `externalsrc` described here https://github.com/openivimobility/meta-oim/pull/127

### CODE REVIEW

**Comment by cajun-rat** [comment]
@alexhumphreys, which version of meta-rust does this go with?

**Comment by alexhumphreys** [comment]
Tested against 4eb46035c535dd6fc1626d08757ddfb72eb796f2
https://github.com/meta-rust/meta-rust/commit/4eb46035c535dd6fc1626d08757ddfb72eb796f2

**Comment by cajun-rat** [comment]
Coolio, I'll make a matching change to the manifest when merging this

**Comment by alexhumphreys** [comment]
Good point, I created https://github.com/advancedtelematic/pro/pull/26 for the manifest files.

**Comment by cajun-rat** [comment]
I'm currently building it now

**Comment by cajun-rat** [comment]
Looks good to me
Review Score: 11/11

**Comment by cajun-rat** [comment]
(Only tested this in qemu, but it could connect OK)

**Pull request merged**
