### PR TITLE
Update sota_client recipe to match Cargo.toml

### PR DESCRIPTION
**Pull request by cajun-rat**
This fixes:
PRO-1713 - OpenIVI fails to build
PRO-1659 - Remove manual steps from the build process

### CODE REVIEW

**Comment by EpicNuts** [comment]
@cajun-rat : Looks good. The client version is updated to tag 0.2.20-pre, but that tag is not listed in the rvi_sota_server repo. Will this cause a conflict?

**Comment by cajun-rat** [comment]
It won't cause a conflict, but I'll check with Shaun about a good tag to build.

**Comment by cajun-rat** [comment]
Updated. It now checks that the make rust-ssl step has completed correctly as a post-compile step.

**Comment by EpicNuts** [comment]
Good stuff :)

**Pull request merged**
