### PR TITLE
Moved DISTRO_FEATURES to local.conf.sample, didn't work in image recipe

### PR DESCRIPTION
**Pull request by OYTIS**
Not sure about VIRTUAL_RUNTIME, it may still work in image recipe, but moving to "conf" would do no harm either.

### CODE REVIEW

**Comment by cajun-rat** [comment]
Why is this better in local.conf than layer.conf?

**Comment by OYTIS** [comment]
Because if it is put in layer.conf, then adding any recipe from meta-oim will require installing x11, for example. I've come upon this problem when I was trying to install ota-plus-client on AGL which uses Wayland.

**Comment by cajun-rat** [comment]
Should we be fixing this by splitting the ota-client recipes into a separate layer?

In order to get the ota-client stuff upstreamed, we will likely need to put it in a separate layer, or merge it into an existing AGL layer.

The reason I'm reluctant to modify local.conf.sample, is that people will need to manually copy any changes that we make into their own local.conf after they have built it for the first time.

**Comment by OYTIS** [comment]
Well, probably. Does everything else in meta-oim depend on x11 and systemd?

**Comment by OYTIS** [comment]
There is a variable calles REQUIRED_DISTRO_FEATURES. It can be set directly in a recipe so that bitbake throws an error if DISTRO_FEATURE isn't enabled. But no way to pull distro feature as a recipe dependency unfortunately.

**Comment by OYTIS** [comment]
Hm... How about defining our own distro? Probably such tunings should be set in distros.

**Pull request closed without merging**
