### PR TITLE
Replace ota-plus-client with rvi_sota_client

### PR DESCRIPTION
**Pull request by alexhumphreys**

### CODE REVIEW

**Comment by cajun-rat** [comment]
Should we rename this recipe too?  What is the OTA Client binary called these days?

**Comment by alexhumphreys** [comment]
Still think it's called ota-plus-client, but I think bitbake pulls the name from the recipe file name, so this binary name might be independent of what's going on in the repo (maybe?). Not sure what the plan is for the name, maybe @taheris can shed some light. Might even be a marketing/usability thing, like, to use Ota+ you install the ota-plus-client, not the rvi_sota_client, which is a bit obtuse.

**Comment by taheris** [comment]
As it stands the binary name in the `rvi_sota_client` repo is still `ota_plus_client` because of merging the two repos and not updating it yet in case it breaks other dependencies. If you are happy from the yocto side of things then I can create a PR to update it.

**Comment by cajun-rat** [comment]
I would suggest that we pick a name for this component: either 'rvi_sota_client' or 'ota_plus_client' and then rename everything to match, i.e the:
- binary
- git repository
- bitbake recipe
- systemd unit
- etc

Since this PR is about adding functionality, I''ve created [PRO-912](https://advancedtelematic.atlassian.net/browse/PRO-912) to track the rename, and I'll merge this now.

**Comment by cajun-rat** [comment]
Review Score: 16/26

**Pull request merged**
